blank_issues_enabled: false
contact_links:
    - name: FAQ | سوالات متداول
      url: https://github.com/bia-pain-bache/BPB-Worker-Panel/blob/main/docs/faq.md
      about: Before asking a question or presenting a problem, read through the frequently asked questions.