name: Build Obfuscate BPB Panel
on:
  push:
    branches:
      - main
  schedule:
    # Runs everyday at 1:00 AM
    - cron: "0 1 * * *"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: |
          npm install -g javascript-obfuscator
      - name: Download and extract BPB repository
        run: |
          # Download as zip to avoid git submodule issues
          wget -O bpb.zip https://github.com/bia-pain-bache/BPB-Worker-Panel/archive/refs/heads/main.zip
          unzip bpb.zip
          echo "Contents after extraction:"
          ls -la
          # Find the actual directory name
          REPO_DIR=$(ls -d BPB-Worker-Panel-* | head -1)
          echo "Found directory: $REPO_DIR"
          mv "$REPO_DIR" bpb-repo
          echo "Repository downloaded and extracted successfully"
          echo "Directory contents:"
          ls -la bpb-repo/
      - name: Build BPB project
        run: |
          cd bpb-repo
          echo "Current directory: $(pwd)"
          echo "Contents:"
          ls -la
          
          # Check if package.json exists
          if [ -f "package.json" ]; then
            echo "Found package.json, installing dependencies..."
            npm install
            echo "Building project..."
            # Check if there's a build script
            echo "Available npm scripts:"
            npm run 2>/dev/null || echo "No scripts available"
            
            if npm run 2>/dev/null | grep -q "build"; then
              echo "Running build script..."
              npm run build
            elif npm run 2>/dev/null | grep -q "compile"; then
              echo "Running compile script..."
              npm run compile
            else
              echo "No build script found, looking for existing worker files..."
            fi
          else
            echo "No package.json found, looking for existing worker files..."
          fi
          
          echo "Final directory contents:"
          find . -name "*.js" | head -10
      - name: Find and copy worker file
        run: |
          cd bpb-repo
          echo "Current directory structure:"
          find . -name "*.js" -type f | head -10
          
          # Look for the main worker file in various locations
          if [ -f "BPB-Worker-Panel-main/src/worker.js" ]; then
            cp BPB-Worker-Panel-main/src/worker.js ../origin.js
            echo "Found worker file in BPB-Worker-Panel-main/src/"
          elif [ -f "src/worker.js" ]; then
            cp src/worker.js ../origin.js
            echo "Found worker file in src/"
          elif [ -f "dist/_worker.js" ]; then
            cp dist/_worker.js ../origin.js
            echo "Found worker file in dist/"
          elif [ -f "build/_worker.js" ]; then
            cp build/_worker.js ../origin.js
            echo "Found worker file in build/"
          elif [ -f "_worker.js" ]; then
            cp _worker.js ../origin.js
            echo "Found worker file in root"
          else
            echo "Could not find worker file in expected locations"
            echo "All JavaScript files found:"
            find . -name "*.js" -type f
            exit 1
          fi
      - name: Verify file was found
        run: |
          if [ ! -f origin.js ]; then
            echo "origin.js file not found"
            exit 1
          fi
          echo "File size: $(wc -c < origin.js) bytes"
          echo "First 10 lines of the file:"
          head -10 origin.js
      - name: Obfuscate BPB worker js
        run: |
          javascript-obfuscator origin.js --output _worker.js \
            --compact true \
            --control-flow-flattening true \
            --control-flow-flattening-threshold 0.75 \
            --dead-code-injection true \
            --dead-code-injection-threshold 0.4 \
            --identifier-names-generator hexadecimal \
            --rename-globals false \
            --string-array true \
            --string-array-encoding 'base64' \
            --string-array-threshold 0.75 \
            --transform-object-keys true \
            --unicode-escape-sequence false \
            --target browser \
            --disable-console-output false
      - name: Verify obfuscated file was created
        run: |
          if [ ! -f _worker.js ]; then
            echo "Obfuscated file was not created"
            exit 1
          fi
          echo "Obfuscated file size: $(wc -c < _worker.js) bytes"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest bpb panel'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
