name: Build Obfuscate BPB Panel
on:
  push:
    branches:
      - main
  schedule:
    # Runs everyday at 1:00 AM
    - cron: "0 1 * * *"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: |
          npm install -g javascript-obfuscator
      - name: Clone BPB work.js
        run: |
          # Download the correct bundled worker file
          if wget -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/dist/_worker.js; then
            echo "Downloaded from dist/_worker.js"
          elif wget -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/_worker.js; then
            echo "Downloaded from _worker.js"
          elif wget -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/_worker.js; then
            echo "Downloaded from build/_worker.js"
          else
            echo "Failed to download worker file from any known location"
            echo "Trying to find the correct file..."
            # List repository contents to help debug
            curl -s https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/contents | grep -E '"name"|"download_url"' || true
            exit 1
          fi
      - name: Verify file was downloaded
        run: |
          if [ ! -f origin.js ]; then
            echo "origin.js file not found"
            exit 1
          fi
          echo "File size: $(wc -c < origin.js) bytes"
          echo "First 5 lines of the file:"
          head -5 origin.js
      - name: Obfuscate BPB worker js
        run: |
          javascript-obfuscator origin.js --output _worker.js \
            --compact true \
            --control-flow-flattening true \
            --control-flow-flattening-threshold 0.75 \
            --dead-code-injection true \
            --dead-code-injection-threshold 0.4 \
            --identifier-names-generator hexadecimal \
            --rename-globals false \
            --string-array true \
            --string-array-encoding 'base64' \
            --string-array-threshold 0.75 \
            --transform-object-keys true \
            --unicode-escape-sequence false \
            --target browser \
            --disable-console-output false
      - name: Verify obfuscated file was created
        run: |
          if [ ! -f _worker.js ]; then
            echo "Obfuscated file was not created"
            exit 1
          fi
          echo "Obfuscated file size: $(wc -c < _worker.js) bytes"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest bpb panel'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
